awk '$4 == chr10' ">" with_id/spCas9_Homo_chr10.tsv
awk '$4 == chr11' ">" with_id/spCas9_Homo_chr11.tsv
awk '$4 == chr12' ">" with_id/spCas9_Homo_chr12.tsv
awk '$4 == chr13' ">" with_id/spCas9_Homo_chr13.tsv
awk '$4 == chr14' ">" with_id/spCas9_Homo_chr14.tsv
awk '$4 == chr15' ">" with_id/spCas9_Homo_chr15.tsv
awk '$4 == chr16' ">" with_id/spCas9_Homo_chr16.tsv
awk '$4 == chr17' ">" with_id/spCas9_Homo_chr17.tsv
awk '$4 == chr18' ">" with_id/spCas9_Homo_chr18.tsv
awk '$4 == chr19' ">" with_id/spCas9_Homo_chr19.tsv
awk '$4 == chr1' ">" with_id/spCas9_Homo_chr1.tsv
awk '$4 == chr20' ">" with_id/spCas9_Homo_chr20.tsv
awk '$4 == chr21' ">" with_id/spCas9_Homo_chr21.tsv
awk '$4 == chr22' ">" with_id/spCas9_Homo_chr22.tsv
awk '$4 == chr2' ">" with_id/spCas9_Homo_chr2.tsv
awk '$4 == chr3' ">" with_id/spCas9_Homo_chr3.tsv
awk '$4 == chr4' ">" with_id/spCas9_Homo_chr4.tsv
awk '$4 == chr5' ">" with_id/spCas9_Homo_chr5.tsv
awk '$4 == chr6' ">" with_id/spCas9_Homo_chr6.tsv
awk '$4 == chr7' ">" with_id/spCas9_Homo_chr7.tsv
awk '$4 == chr8' ">" with_id/spCas9_Homo_chr8.tsv
awk '$4 == chr9' ">" with_id/spCas9_Homo_chr9.tsv
awk '$4 == chrX' ">" with_id/spCas9_Homo_chrX.tsv
awk '$4 == chrY' ">" with_id/spCas9_Homo_chrY.tsv
