python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr1
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr2
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr3
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr4
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr5
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr6
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr7
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr8
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr9
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr10
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr11
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr12
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr13
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr14
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr15
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr16
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr17
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr18
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr19
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr20
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr21
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chr22
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chrX
python /mnt/ntc_data/wayne/Repositories/CRISPR/process_border_withid.py chrY